### PR TITLE
Adding ability to store names.

### PR DESCRIPTION
**Pull request by vprusso**
Related: https://github.com/unitaryfund/metriq-app/pull/605

### CODE REVIEW

**Review by WrathfulSpatula — CHANGES_REQUESTED** [review]
You need a migration for this, (as well as the model update you already have). Remember, we should be able to sync the database schema just by running the latest migrations.

**Comment by vprusso** [comment]
@WrathfulSpatula I'm guessing I run migrations so infrequently that I always forget how to do this. Is this the correct command?

```
npm run db:migrate       

If so, I'm getting the following issue. I'm most likely forgetting to do something trivial here. 
```
npm ERR! Missing script: "db:migrate"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincent.russo/.npm/_logs/2022-06-28T20_43_28_493Z-debug.log
```

**Comment by vprusso** [comment]
Hmm. So it does work, but the migration does work in the sense that nothing breaks but it appears as if nothing is applied. 

Again, I'm probably just forgetting to do something really dumb here:

```
> metriq-api@0.1.0 db:migrate
> babel-node ./scripts/db/migrate


Sequelize CLI [Node: 14.17.0, CLI: 6.4.1, ORM: 6.12.4]

Parsed url postgres://metriq:*****@localhost:5432/metriq
No migrations were executed, database schema was already up to date.
*************************
Migration successful
```

**Comment by WrathfulSpatula** [comment]
@vprusso You have to manually write the migration. Look at the previous ones for examples, and code the new migration file. You start out creating the stub with `npm run db:migrate`.

**Comment by vprusso** [comment]
> @vprusso You have to manually write the migration. Look at the previous ones for examples, and code the new migration file. You start out creating the stub with `npm run db:migrate`.

Ah okay. Adding that here:
https://github.com/unitaryfund/metriq-api/pull/194/commits#:~:text=Adding%20migration%20file.

**Comment by vprusso** [comment]
> The migration looks good, for a single column. Do make sure that you can run it both "up" and "down" several times, and that it leaves your development database in the right schema state. For more complicated migrations with multiple columns/tables/etc., you'd want to wrap them all in the same atomic transaction, but you only add a single column, here, so it's fine.

Gotcha. So I think the following output here is okay:

```
➜  metriq-api git:(602_include_register_name) ✗ npm run db:migrate up

> metriq-api@0.1.0 db:migrate
> babel-node ./scripts/db/migrate "up"


Sequelize CLI [Node: 14.17.0, CLI: 6.4.1, ORM: 6.12.4]

Parsed url postgres://metriq:*****@localhost:5432/metriq
No migrations were executed, database schema was already up to date.
*************************
Migration successful
➜  metriq-api git:(602_include_register_name) ✗ npm run db:migrate down

> metriq-api@0.1.0 db:migrate
> babel-node ./scripts/db/migrate "down"


Sequelize CLI [Node: 14.17.0, CLI: 6.4.1, ORM: 6.12.4]

Parsed url postgres://metriq:*****@localhost:5432/metriq
No migrations were executed, database schema was already up to date.
*************************
Migration successful
```

If so, I can go ahead and merge @WrathfulSpatula

**Comment by WrathfulSpatula** [comment]
LGTM, @vprusso!

**Pull request merged**
