### PR TITLE
Ability for affiliation and name to be blank on registration.

### PR DESCRIPTION
**Pull request by vprusso**
Closes #603

### CODE REVIEW

**Review by WrathfulSpatula — CHANGES_REQUESTED** [review]
@vprusso, Sorry, but this isn't right. Firstly, like we said, empty string is preferable wherever it can stand in for nullable columns, so we _don't_ want these columns to be nullable. Also, changing whether a column is nullable requires another migration, since basically the entirely model definition here actually corresponds to properties of the SQL database, which would need to be changed in there in the database. However, you don't want to make these nullable, and so you don't need a migration.

The code you're probably looking for is in "_service layer_," not "_model layer_" where this original change is. Basically, values inserted into these model fields _in the service classes_ should check for "falsey" values being placed in these columns, and it should replace "falsely" values like `undefined` or `null` with empty string, `''`. That's all you have to do here, if it isn't already handled. You'll see examples of patterns already in the service classes that look like `column = request.column ? request.column : ''`.

**Comment by WrathfulSpatula** [comment]
The validation might need an update, too, if it considers these fields required as opposed to optional, but it's just a matter of the "service layer."

**Comment by vprusso** [comment]
Hmm, in that case, given the already existing lines of:

```javascript
    user.affiliation = reqBody.affiliation ? reqBody.affiliation :  ''
    user.name = reqBody.name ? reqBody.name :  ''
```

in `userService.js` it seems like it this is already accounted for in which case, perhaps this branch should be abandoned and the #195 issue be closed? @WrathfulSpatula

**Comment by WrathfulSpatula** [comment]
@vprusso That sounds right. Good work on forming a plan ahead, if only for due diligence of gaining context in the code base and technological framework.

**Comment by vprusso** [comment]
> @vprusso That sounds right. Good work on forming a plan ahead, if only for due diligence of gaining context in the code base and technological framework.

Thanks for the kind words and explanation. With that, I'll go ahead and close this out. Thanks again for the feedback!

**Pull request closed without merging**
